routes/web.php
<?php

use App\Http\Controllers\Auth\Services\TrelloController;
use App\Http\Controllers\Crud\ClientsController;
use App\Http\Controllers\Crud\ContactPersonsController;
use App\Http\Controllers\Crud\LaborCostsController;
use App\Http\Controllers\Crud\LeadsController;
use App\Http\Controllers\Crud\PermissionsController;
use App\Http\Controllers\Crud\ProjectsController;
use App\Http\Controllers\Crud\ProjectsTasksController;
use App\Http\Controllers\PagesController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Crud\UsersController;
use App\Http\Controllers\Crud\RolesController;

Route::middleware('auth')->group(function () {

    Route::prefix('users')->group(function () {

        Route::resource('staff', UsersController::class);

        Route::resource('permissions', PermissionsController::class);

        Route::resource('roles', RolesController::class);
    });

    Route::prefix('client-management')->group(function () {

        Route::resource('contact-persons', ContactPersonsController::class);

//        Подписание ммаршрута контактного лица
        Route::post('contact-persons/{id}/share', [ContactPersonsController::class, 'signed'])->name('contact-persons.signed');

        Route::name('leads.')->prefix('leads')->group(function () {
            Route::get('in-process', [LeadsController::class, 'inProcess'])->name('in-process');
            Route::get('cotton', [LeadsController::class, 'cotton'])->name('cotton');
            Route::get('failed', [LeadsController::class, 'failed'])->name('failed');
        });
        Route::resource('leads', ClientsController::class, ['except' => ['index', 'store', 'update', 'delete']]);
        Route::name('clients.')->prefix('clients')->group(function () {
            Route::get('active', [ClientsController::class, 'active'])->name('active');
            Route::get('archive', [ClientsController::class, 'archive'])->name('archive');
        });
        Route::resource('clients', ClientsController::class);

        Route::resource('projects', ProjectsController::class, ['except' => ['store', 'update', 'delete']])->names('projects');

        Route::resource('projects.tasks', ProjectsTasksController::class)->except([
            'index', 'delete', 'show'
        ]);
    });

    Route::resource('laborcosts', LaborCostsController::class, ['except' => ['store', 'show']]);

    Route::get('/', [PagesController::class, 'dashboard'])->name('dashboard');

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

/*
 * oauth
 * */
Route::get('/login/trello', [TrelloController::class, 'redirectToProvider'])->name('login.trello');
Route::get('/login/trello/callback', [TrelloController::class, 'handleProviderCallback']);

// Отображение подписанного маршрута контактного лица
Route::get('/contact-person/{id}/share', [ContactPersonsController::class, 'share'])->name('contact-persons.share');

Route::view('/welcome', 'welcome');
Route::get('/test', function () {
    Auth::attempt([
        'name' => 'Admin',
        'password' => 'password'
    ]);
});

require __DIR__ . '/auth.php';

app/Http/Controllers/Crud/BaseCrudController.php
<?php


namespace App\Http\Controllers\Crud;


use App\Http\Controllers\Controller;

abstract class BaseCrudController extends Controller
{

}

app/Http/Controllers/Crud/ClientsController.php
<?php

namespace App\Http\Controllers\Crud;

use App\Http\Requests\Crud\CreateClientRequest;
use App\Http\Requests\Crud\UpdateClientRequest;
use App\Models\City;
use App\Models\Client;
use App\Models\Lead;
use App\Models\OrganizationalForms;
use App\Models\Project;
use App\Models\User;
use App\UseCases\Clients\CrudClientUseCase;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use App\Enums\ClientStatusEnum;

class ClientsController extends BaseCrudController
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        abort_if(Gate::denies('clients_index'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $clients = Client::get();

        return view('pages.crud.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        abort_if(Gate::denies('clients_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $leads = Lead::get()->pluck('name', 'id');
        $cities = City::get()->pluck('name', 'id');
        $organizationalForms = OrganizationalForms::orderBy('sort', 'asc')->get()->pluck('name', 'id');
        $managers = User::role('Менеджер')->get();

        return view('pages.crud.clients.create', compact('leads', 'cities', 'organizationalForms', 'managers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateClientRequest $request
     * @return RedirectResponse
     */
    public function store(CreateClientRequest $request): RedirectResponse
    {
        CrudClientUseCase::createClient($request->only('client'), $request->only('legal-data'));

        return redirect()->route('clients.index')->with('success', 'Клиент успешно создан!');
    }

    /**
     * Display the specified resource.
     *
     * @param Client $client
     * @return Application|Factory|View|Response
     */
    public function show(Client $client)
    {
        abort_if(Gate::denies('clients_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $projects = Project::with('childService')->where('client_id', $client->id)->limit(4)->orderByDesc('id')->get();

        $users = User::whereHas('projects', function ($query) use ($client) {
            $query->where('client_id', $client->id);
        })->get();

        return view('pages.crud.clients.show', compact('client', 'projects', 'users'));
    }

    /**
     * Display a listing with status active of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function active()
    {
        abort_if(Gate::denies('clients_index'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $clients = Client::where('status', '=', ClientStatusEnum::ACTIVE_STATUS)->orderByDesc('id')->get();

        return view('pages.crud.clients.index', compact('clients'));
    }

    public function archive()
    {
        abort_if(Gate::denies('clients_index'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $clients = Client::where('status', '=', ClientStatusEnum::ARCHIVE_STATUS)->orderByDesc('id')->get();

        return view('pages.crud.clients.index', compact('clients'));
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param Client $client
     * @return Application|Factory|View|Response
     */
    public function edit(Client $client)
    {
        abort_if(Gate::denies('clients_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $leads = Lead::get()->pluck('name', 'id');
        $cities = City::get()->pluck('name', 'id');
        $organizationalForms = OrganizationalForms::orderBy('sort', 'asc')->get()->pluck('name', 'id');
        $managers = User::role('Менеджер')->get();

        return view('pages.crud.clients.edit', compact('client', 'leads', 'cities', 'organizationalForms', 'managers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateClientRequest $request
     * @param Client $client
     * @return RedirectResponse
     */
    public function update(UpdateClientRequest $request, Client $client)
    {
        CrudClientUseCase::updateClient($client, $request->only('client'), $request->only('legal-data'));

        return redirect()->route('clients.index')->with('success', 'Клиент успешно обновлен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Crud/ContactPersonsController.php
<?php

namespace App\Http\Controllers\Crud;

use App\Http\Requests\Crud\CreateContactPersonRequest;
use App\Http\Requests\Crud\UpdateContactPersonRequest;
use App\Models\ContactPerson;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\URL;

class ContactPersonsController extends BaseCrudController
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        abort_if(Gate::denies('contact-persons__index'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $contactPersons = ContactPerson::orderByDesc('created_at')->paginate(16);

        return view('pages.crud.contact-persons.index', compact('contactPersons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        abort_if(Gate::denies('contact-persons_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('pages.crud.contact-persons.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateContactPersonRequest $request
     * @return RedirectResponse
     */
    public function store(CreateContactPersonRequest $request)
    {
        ContactPerson::create($request->only('name', 'email', 'phone', 'comment'));

        return redirect()->route('contact-persons.index')->with('success', 'Контактное лицо успешно создано');
    }

    /**
     * Display the specified resource.
     *
     * @param ContactPerson $contactPerson
     * @return Application|Factory|View|Response
     */
    public function show(ContactPerson $contactPerson)
    {
        abort_if(Gate::denies('contact-persons_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('pages.crud.contact-persons.show', compact('contactPerson'));
    }

    /**
     * Возвращает ссылку на кантакты которая будет активна в течении часа
     * @param $id
     * @return string
     */
    public function signed($id)
    {
        return URL::temporarySignedRoute('contact-persons.share', now()->addMinutes(60), ['id' => $id]);
    }

    /**
     * Осуществляет проверку на подлинность ссылки и отображает контакт
     * @param Request $request
     * @param $id
     * @return Application|Factory|View
     */
    public function share(Request $request, $id)
    {
        if (! request()->hasValidSignature()) {
            abort(401);
        }
        $contactPerson = ContactPerson::findOrFail($id);

        return view('pages.crud.contact-persons.share', compact('contactPerson'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param ContactPerson $contactPerson
     * @return Application|Factory|View|Response
     */
    public function edit(ContactPerson $contactPerson)
    {
        abort_if(Gate::denies('contact-persons_update'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('pages.crud.contact-persons.edit', compact('contactPerson'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateContactPersonRequest $request
     * @param ContactPerson $contactPerson
     * @return RedirectResponse
     */
    public function update(UpdateContactPersonRequest $request, ContactPerson $contactPerson)
    {
        $contactPerson->name = $request->input('name');
        $contactPerson->email = $request->input('email');
        $contactPerson->phone = $request->input('phone');
        $contactPerson->comment = $request->input('comment', '');
        $contactPerson->save();

        return redirect()->route('contact-persons.index')->with('success', 'Контактное лицо успешно обновлено');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param ContactPerson $contactPerson
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(ContactPerson $contactPerson)
    {
        abort_if(Gate::denies('contact-persons_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $contactPerson->delete();

        return redirect()->route('contact-persons.index')->with('success', 'Контакты были успешно удалены');
    }
}

app/Http/Controllers/Crud/LaborCostsController.php
<?php

namespace App\Http\Controllers\Crud;

use App\Enums\ProjectStatusEnum;
use App\Http\Requests\Crud\UpdateLaborCostsRequest;
use App\Models\LaborCost;
use App\Models\Project;
use App\Models\Task;
use Carbon\Carbon;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;

class LaborCostsController extends BaseCrudController
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        abort_if(Gate::denies('laborcosts_index'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $laborcosts = LaborCost::where('user_id', auth()->user()->id)->get();

        return view('pages.crud.labor-costs.index', compact('laborcosts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        abort_if(Gate::denies('laborcosts_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('pages.crud.labor-costs.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param LaborCost $laborcost
     * @return Application|Factory|View|Response
     */
    public function edit(LaborCost $laborcost)
    {
        abort_if(Gate::denies('laborcosts_update'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tasks = Task::whereHas('project', function ($query) {
            $query->where('status', '=', ProjectStatusEnum::IN_PROCESS_STATUS);
        })->where('user_id', '=', auth()->user()->id)->get();

        return view('pages.crud.labor-costs.edit', compact('laborcost', 'tasks'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateLaborCostsRequest $request
     * @param LaborCost $laborcost
     * @return RedirectResponse
     */
    public function update(UpdateLaborCostsRequest $request, LaborCost $laborcost): RedirectResponse
    {
        $laborcost->fill($request->only([
            'description',
            'task_id',
            'spent_time',
        ]));

        $laborcost->created_at = Carbon::createFromFormat('Y-m-d\TH:i', $request->input('created_at'))->format('Y-m-d H:i:s');
        $laborcost->save();

        session()->flash('success', 'Трудозатрата успешно обновлена');

        return redirect()->route('laborcosts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param LaborCost $laborcost
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(LaborCost $laborcost): RedirectResponse
    {
        abort_if(Gate::denies('laborcosts_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $laborcost->delete();
        session()->flash('success', 'Трудозатрата успешно удалена!');
        return redirect()->route('laborcosts.index');
    }
}

app/Http/Controllers/Crud/PermissionsController.php
<?php

namespace App\Http\Controllers\Crud;

use App\Http\Requests\Crud\CreatePermissionRequest;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use Spatie\Permission\Models\Permission;

class PermissionsController extends BaseCrudController
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        abort_if(Gate::denies('permission_index'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $permissions = Permission::get();

        return view('pages.crud.permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        abort_if(Gate::denies('permission_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('pages.crud.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreatePermissionRequest $request
     * @return RedirectResponse
     */
    public function store(CreatePermissionRequest $request): RedirectResponse
    {
        Permission::create($request->only('name'));

        return redirect()->route('permissions.index')->with('success', 'Разрешение успешно создано');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Permission $permission
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(Permission $permission)
    {
        abort_if(Gate::denies('permission__delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $permission->delete();

        return redirect()->route('permissions.index')->with('success', 'Разрешение успешно удалено');
    }
}

resources/views/pages/crud/roles/create.blade.php
@extends('layouts.backend')

@section('css_before')
    <!-- Page JS Plugins CSS -->
    <link rel="stylesheet" href="{{ asset('js/plugins/select2/css/select2.min.css') }}">
@endsection

@section('js_after')
    <!-- Page JS Plugins -->
    <script src="{{ asset('js/plugins/select2/js/select2.full.min.js') }}"></script>
{{--    <script src="{{ asset('js/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>--}}

    <!-- Page JS Code -->
    <script>jQuery(function(){ Codebase.helpers(['select2']); });</script>
{{--    <script src="{{ asset('js/pages/tables_datatables.js') }}"></script>--}}
@endsection

@section('content')
    @include('partials.ui.h2', ['title' => 'Создание роли'])
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">
                <i class="fa fa-pencil fa-fw mr-5 text-muted"></i> Роль
            </h3>
        </div>
        <div class="block-content">
            <div class="row items-push">
                <div class="col-lg-3">
                    <p class="text-muted">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, quae?
                    </p>
                </div>
                <div class="col-lg-7 offset-lg-1">
                    <form action="{{ route('roles.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="hosting-settings-profile-name">Название роли</label>
                            <input type="text" class="form-control form-control-lg" name="name" placeholder="Введите название роли.." value="{{ old('name') }}">
                        </div>

                        <div class="form-group row">
                            <label class="col-12" for="example-select2-multiple">Разрешения</label>
                            <div class="col-lg-12">
                                <select class="js-select2 form-control" id="example-select2-multiple" name="permissions[]" style="width: 100%;" data-placeholder="Выберите разрешения.." multiple>
                                    @foreach($permissions as $permission)
                                        <option value="{{ $permission->id }}">{{ $permission->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-alt-primary">Создать</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/crud/roles/edit.blade.php
@extends('layouts.backend')

@section('css_before')
    <!-- Page JS Plugins CSS -->
    <link rel="stylesheet" href="{{ asset('js/plugins/select2/css/select2.min.css') }}">
@endsection

@section('js_after')
    <!-- Page JS Plugins -->
    <script src="{{ asset('js/plugins/select2/js/select2.full.min.js') }}"></script>rap4.min.js') }}"></script>--}}

    <!-- Page JS Code -->
    <script>jQuery(function(){ Codebase.helpers(['select2']); });</script>
@endsection

@section('content')
    @include('partials.ui.h2', ['title' => 'Редактирование роли'])
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">
                <i class="fa fa-pencil fa-fw mr-5 text-muted"></i> Роль
            </h3>
        </div>
        <div class="block-content">
            <div class="row items-push">
                <div class="col-lg-3">
                    <p class="text-muted">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, quae?
                    </p>
                </div>
                <div class="col-lg-7 offset-lg-1">
                    <form action="{{ route('roles.update', $role->id) }}" method="POST">
                        @csrf
                        @method('PATCH')
                        <div class="form-group">
                            <label for="hosting-settings-profile-name">Название роли</label>
                            <input type="text" class="form-control form-control-lg" name="name" placeholder="Введите название роли.." value="{{ old('name') ?? $role->name }}">
                        </div>

                        <div class="form-group row">
                            <label class="col-12" for="example-select2-multiple">Разрешения</label>
                            <div class="col-lg-12">
                                <select class="js-select2 form-control" id="example-select2-multiple" name="permissions[]" style="width: 100%;" data-placeholder="Выберите разрешения.." multiple>
                                    @foreach($permissions as $id => $permission)
                                        <option value="{{ $id }}" {{ (in_array($id, old('permissions', [])) || $role->permissions->contains($id)) ? 'selected' : '' }}>{{ $permission }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-alt-primary">Обновить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/crud/roles/index.blade.php
@extends('layouts.backend')

@section('css_before')
    <!-- Page JS Plugins CSS -->
    <link rel="stylesheet" href="{{ asset('js/plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection

@section('js_after')
    <!-- Page JS Plugins -->
    <script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page JS Code -->
    <script src="{{ asset('js/pages/tables_datatables.js') }}"></script>
@endsection

@section('content')
    @include('partials.ui.h2', ['title' => 'Пользователи'])
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Роли</h3>
            @can('role_create')
                @include('partials.ui.create-button', ['name' => 'роль', 'link' => route('roles.create')])
            @endcan
        </div>
        <div class="block-content block-content-full">
            <!-- DataTables functionality is initialized with .js-dataTable-full class in js/pages/be_tables_datatables.min.js which was auto compiled from _es6/pages/be_tables_datatables.js -->
            <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                <thead>
                <tr>
                    <th class="text-center"></th>
                    <th>Название</th>
                    <th class="text-center" style="width: 15%;"></th>
                </tr>
                </thead>
                <tbody>
                @foreach($roles as $role)
                    <tr>
                        <td class="text-center">{{ $role->id }}</td>
                        <td class="font-w600">{{ $role->name }}</td>
                        <td class="text-center">
                            <div class="btn-group">
                                @can('role_update')
                                    @include('partials.ui.edit-table-button', [
                                        'route' => route('roles.edit', $role->id)
                                    ])
                                @endcan
                                @can('role_delete')
                                    @include('partials.ui.delete-table-button', [
                                        'confirm' => 'Вы действивтельно хотите удалить роль ' . $role->name,
                                        'formId' => "delete-role" . $role->id . "-form",
                                        'route' => route('roles.destroy', $role->id)
                                    ])
                                @endcan
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection